# Generated by Django 5.0 on 2024-01-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_yet', models.BooleanField(blank=True, default='False', null=True)),
                ('AvocatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.avocats')),
            ],
        ),
    ]
