# Generated by Django 5.0 on 2024-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='Date_rendezvous',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
