# Generated by Django 5.0 on 2024-01-26 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0002_rendez_vous_date_rendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='Date_rendezvous',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
