# Generated by Django 5.0 on 2024-01-26 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avocats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('domaine_juridique', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(default='', max_length=128)),
                ('numero_telephone', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must start with 05, 06, or 07 and be 10 digits long.', regex='^(05|06|07)[0-9]{8}$'), django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)])),
                ('competences', models.CharField(default='', max_length=20)),
                ('experiences', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('last_name', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
